//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SBSResourceAPI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SBSResourceAPI.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledge.
        /// </summary>
        public static string Acknowledge {
            get {
                return ResourceManager.GetString("Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action taken.
        /// </summary>
        public static string Action_Taken {
            get {
                return ResourceManager.GetString("Action_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Weight.
        /// </summary>
        public static string Actual_Weight {
            get {
                return ResourceManager.GetString("Actual_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Template Components.
        /// </summary>
        public static string Add_Template_Components {
            get {
                return ResourceManager.GetString("Add_Template_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Filter.
        /// </summary>
        public static string Apply_Filter {
            get {
                return ResourceManager.GetString("Apply_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval by Management.
        /// </summary>
        public static string Approval_By_Management {
            get {
                return ResourceManager.GetString("Approval_By_Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Template to Product.
        /// </summary>
        public static string Assign_Template_To_Product {
            get {
                return ResourceManager.GetString("Assign_Template_To_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment File.
        /// </summary>
        public static string Attachment_File {
            get {
                return ResourceManager.GetString("Attachment_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized.
        /// </summary>
        public static string Authorized {
            get {
                return ResourceManager.GetString("Authorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized By.
        /// </summary>
        public static string Authorized_By {
            get {
                return ResourceManager.GetString("Authorized_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorized Date.
        /// </summary>
        public static string Authorized_Date {
            get {
                return ResourceManager.GetString("Authorized_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Field.
        /// </summary>
        public static string Btn_Add_New_Field {
            get {
                return ResourceManager.GetString("Btn_Add_New_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Header.
        /// </summary>
        public static string Btn_Add_New_Header {
            get {
                return ResourceManager.GetString("Btn_Add_New_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Btn_Back {
            get {
                return ResourceManager.GetString("Btn_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Btn_Clear {
            get {
                return ResourceManager.GetString("Btn_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Btn_Download {
            get {
                return ResourceManager.GetString("Btn_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Btn_OK {
            get {
                return ResourceManager.GetString("Btn_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Btn_Upload {
            get {
                return ResourceManager.GetString("Btn_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carried out by.
        /// </summary>
        public static string Carried_Out_By {
            get {
                return ResourceManager.GetString("Carried_Out_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Carried_Out_Date {
            get {
                return ResourceManager.GetString("Carried_Out_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charge Date.
        /// </summary>
        public static string Charge_Date {
            get {
                return ResourceManager.GetString("Charge_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Control.
        /// </summary>
        public static string Charging_Control {
            get {
                return ResourceManager.GetString("Charging_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Charging Drum.
        /// </summary>
        public static string Charging_Drum {
            get {
                return ResourceManager.GetString("Charging_Drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Monitoring System.
        /// </summary>
        public static string Chemical_Monitoring_System {
            get {
                return ResourceManager.GetString("Chemical_Monitoring_System", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose.
        /// </summary>
        public static string Choose {
            get {
                return ResourceManager.GetString("Choose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone.
        /// </summary>
        public static string Clone {
            get {
                return ResourceManager.GetString("Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Rejection.
        /// </summary>
        public static string Close_Rejection {
            get {
                return ResourceManager.GetString("Close_Rejection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Charge.
        /// </summary>
        public static string CMS_Charge {
            get {
                return ResourceManager.GetString("CMS_Charge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Delivery.
        /// </summary>
        public static string CMS_Delivery {
            get {
                return ResourceManager.GetString("CMS_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Purge.
        /// </summary>
        public static string CMS_Purge {
            get {
                return ResourceManager.GetString("CMS_Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CMS Setup.
        /// </summary>
        public static string CMS_Setup {
            get {
                return ResourceManager.GetString("CMS_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C.O.A.
        /// </summary>
        public static string COA {
            get {
                return ResourceManager.GetString("COA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer.
        /// </summary>
        public static string Customer {
            get {
                return ResourceManager.GetString("Customer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8D No..
        /// </summary>
        public static string D8_No {
            get {
                return ResourceManager.GetString("D8_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily Production Planning.
        /// </summary>
        public static string Daily_Production_Planning {
            get {
                return ResourceManager.GetString("Daily_Production_Planning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Type.
        /// </summary>
        public static string Data_Type {
            get {
                return ResourceManager.GetString("Data_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Charged.
        /// </summary>
        public static string Date_Charged {
            get {
                return ResourceManager.GetString("Date_Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Delivered.
        /// </summary>
        public static string Date_Delivered {
            get {
                return ResourceManager.GetString("Date_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date From.
        /// </summary>
        public static string Date_From {
            get {
                return ResourceManager.GetString("Date_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Printed.
        /// </summary>
        public static string Date_Printed {
            get {
                return ResourceManager.GetString("Date_Printed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Purge.
        /// </summary>
        public static string Date_Purge {
            get {
                return ResourceManager.GetString("Date_Purge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date Range.
        /// </summary>
        public static string Date_Range {
            get {
                return ResourceManager.GetString("Date_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date To.
        /// </summary>
        public static string Date_To {
            get {
                return ResourceManager.GetString("Date_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect.
        /// </summary>
        public static string Defect {
            get {
                return ResourceManager.GetString("Defect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defect Description.
        /// </summary>
        public static string Defect_Description {
            get {
                return ResourceManager.GetString("Defect_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivered.
        /// </summary>
        public static string Delivered {
            get {
                return ResourceManager.GetString("Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery.
        /// </summary>
        public static string Delivery {
            get {
                return ResourceManager.GetString("Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery - Download Order.
        /// </summary>
        public static string Delivery_Download_Order {
            get {
                return ResourceManager.GetString("Delivery_Download_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Order No..
        /// </summary>
        public static string Delivery_Order_No {
            get {
                return ResourceManager.GetString("Delivery_Order_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Status.
        /// </summary>
        public static string Delivery_Status {
            get {
                return ResourceManager.GetString("Delivery_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery - Upload Delivery.
        /// </summary>
        public static string Delivery_Upload_Delivery {
            get {
                return ResourceManager.GetString("Delivery_Upload_Delivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Upload Order.
        /// </summary>
        public static string Delivery_Upload_Order {
            get {
                return ResourceManager.GetString("Delivery_Upload_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dented.
        /// </summary>
        public static string Dented {
            get {
                return ResourceManager.GetString("Dented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail.
        /// </summary>
        public static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dilution Tank No..
        /// </summary>
        public static string Dilution_Tank_No {
            get {
                return ResourceManager.GetString("Dilution_Tank_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Product Form Field.
        /// </summary>
        public static string Display_Product_Form_Field {
            get {
                return ResourceManager.GetString("Display_Product_Form_Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose Externally.
        /// </summary>
        public static string Dispose_Externally {
            get {
                return ResourceManager.GetString("Dispose_Externally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose Internally.
        /// </summary>
        public static string Dispose_Internally {
            get {
                return ResourceManager.GetString("Dispose_Internally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dispose Internally / Dispose Externally.
        /// </summary>
        public static string Dispose_Internally_OR_Dispose_Externally {
            get {
                return ResourceManager.GetString("Dispose_Internally_OR_Dispose_Externally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition.
        /// </summary>
        public static string Disposition {
            get {
                return ResourceManager.GetString("Disposition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition Action By.
        /// </summary>
        public static string Disposition_Action_By {
            get {
                return ResourceManager.GetString("Disposition_Action_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition Date.
        /// </summary>
        public static string Disposition_Date {
            get {
                return ResourceManager.GetString("Disposition_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework.
        /// </summary>
        public static string Disposition_Rework {
            get {
                return ResourceManager.GetString("Disposition_Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTE.
        /// </summary>
        public static string Disposition_RTS {
            get {
                return ResourceManager.GetString("Disposition_RTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        public static string Disposition_Scrap {
            get {
                return ResourceManager.GetString("Disposition_Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAI.
        /// </summary>
        public static string Disposition_UAI {
            get {
                return ResourceManager.GetString("Disposition_UAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop-down List.
        /// </summary>
        public static string DropDownList {
            get {
                return ResourceManager.GetString("DropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum Code.
        /// </summary>
        public static string Drum_Code {
            get {
                return ResourceManager.GetString("Drum_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum Control.
        /// </summary>
        public static string Drum_Control {
            get {
                return ResourceManager.GetString("Drum_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum History Report.
        /// </summary>
        public static string Drum_History_Report {
            get {
                return ResourceManager.GetString("Drum_History_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drum Types.
        /// </summary>
        public static string Drum_Types {
            get {
                return ResourceManager.GetString("Drum_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Notification.
        /// </summary>
        public static string Email_Notification {
            get {
                return ResourceManager.GetString("Email_Notification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry Date.
        /// </summary>
        public static string Expiry_Date {
            get {
                return ResourceManager.GetString("Expiry_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string Export_Excel {
            get {
                return ResourceManager.GetString("Export_Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External Provider.
        /// </summary>
        public static string External_Provider {
            get {
                return ResourceManager.GetString("External_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string Failed {
            get {
                return ResourceManager.GetString("Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field From.
        /// </summary>
        public static string Field_From {
            get {
                return ResourceManager.GetString("Field_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Name.
        /// </summary>
        public static string Field_Name {
            get {
                return ResourceManager.GetString("Field_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fields.
        /// </summary>
        public static string Fields {
            get {
                return ResourceManager.GetString("Fields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling Process.
        /// </summary>
        public static string Filling_Process {
            get {
                return ResourceManager.GetString("Filling_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filling Stations.
        /// </summary>
        public static string Filling_Stations {
            get {
                return ResourceManager.GetString("Filling_Stations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final Weight.
        /// </summary>
        public static string Final_Weight {
            get {
                return ResourceManager.GetString("Final_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods.
        /// </summary>
        public static string Finished_Goods {
            get {
                return ResourceManager.GetString("Finished_Goods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished Goods Lot No..
        /// </summary>
        public static string Finished_Goods_Lot_No {
            get {
                return ResourceManager.GetString("Finished_Goods_Lot_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form No..
        /// </summary>
        public static string Form_No {
            get {
                return ResourceManager.GetString("Form_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format Code.
        /// </summary>
        public static string Format_Code {
            get {
                return ResourceManager.GetString("Format_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatting.
        /// </summary>
        public static string Formatting {
            get {
                return ResourceManager.GetString("Formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form No..
        /// </summary>
        public static string From_No {
            get {
                return ResourceManager.GetString("From_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Time.
        /// </summary>
        public static string From_Time {
            get {
                return ResourceManager.GetString("From_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Weight (F).
        /// </summary>
        public static string Get_Weight_F {
            get {
                return ResourceManager.GetString("Get_Weight_F", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Weight (I).
        /// </summary>
        public static string Get_Weight_I {
            get {
                return ResourceManager.GetString("Get_Weight_I", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Lookup.
        /// </summary>
        public static string Global_Lookup {
            get {
                return ResourceManager.GetString("Global_Lookup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval by GM.
        /// </summary>
        public static string GM_Approval_Date {
            get {
                return ResourceManager.GetString("GM_Approval_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go To Home.
        /// </summary>
        public static string Go_To_Home {
            get {
                return ResourceManager.GetString("Go_To_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        public static string Group_Name {
            get {
                return ResourceManager.GetString("Group_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groups.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guranteed Date.
        /// </summary>
        public static string Guranteed_Date {
            get {
                return ResourceManager.GetString("Guranteed_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        public static string Header {
            get {
                return ResourceManager.GetString("Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Name.
        /// </summary>
        public static string Header_Name {
            get {
                return ResourceManager.GetString("Header_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        public static string Headers {
            get {
                return ResourceManager.GetString("Headers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hole.
        /// </summary>
        public static string Hole {
            get {
                return ResourceManager.GetString("Hole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income Raw Material.
        /// </summary>
        public static string Income_Raw_Material {
            get {
                return ResourceManager.GetString("Income_Raw_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Raw Material.
        /// </summary>
        public static string Incoming_Raw_Material {
            get {
                return ResourceManager.GetString("Incoming_Raw_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Raw Material Checklist.
        /// </summary>
        public static string Incoming_Raw_Material_Checklist {
            get {
                return ResourceManager.GetString("Incoming_Raw_Material_Checklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Raw Material Report.
        /// </summary>
        public static string Incoming_Raw_Material_Report {
            get {
                return ResourceManager.GetString("Incoming_Raw_Material_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In house.
        /// </summary>
        public static string Inhouse {
            get {
                return ResourceManager.GetString("Inhouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial Weight.
        /// </summary>
        public static string Initial_Weight {
            get {
                return ResourceManager.GetString("Initial_Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions.
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Report.
        /// </summary>
        public static string Inventory_Report {
            get {
                return ResourceManager.GetString("Inventory_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice.
        /// </summary>
        public static string Invoice {
            get {
                return ResourceManager.GetString("Invoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is duplicated..
        /// </summary>
        public static string Is_Duplicated {
            get {
                return ResourceManager.GetString("Is_Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is Inccorect..
        /// </summary>
        public static string Is_Inccorect {
            get {
                return ResourceManager.GetString("Is_Inccorect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required..
        /// </summary>
        public static string Is_Required {
            get {
                return ResourceManager.GetString("Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to is required..
        /// </summary>
        public static string Is_Rrequired {
            get {
                return ResourceManager.GetString("Is_Rrequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LDAP Username.
        /// </summary>
        public static string LDAP_Username {
            get {
                return ResourceManager.GetString("LDAP_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave as textbox.
        /// </summary>
        public static string Leave_As_Textbox {
            get {
                return ResourceManager.GetString("Leave_As_Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Delivery Order Scanned.
        /// </summary>
        public static string List_Of_Delivery_Order_Scanned {
            get {
                return ResourceManager.GetString("List_Of_Delivery_Order_Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of Delivery Uploaded.
        /// </summary>
        public static string List_Of_Delivery_Uploaded {
            get {
                return ResourceManager.GetString("List_Of_Delivery_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics.
        /// </summary>
        public static string Logistics {
            get {
                return ResourceManager.GetString("Logistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logistics Date.
        /// </summary>
        public static string Logistics_Date {
            get {
                return ResourceManager.GetString("Logistics_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheet.
        /// </summary>
        public static string Logsheet {
            get {
                return ResourceManager.GetString("Logsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheet Information.
        /// </summary>
        public static string Logsheet_Info {
            get {
                return ResourceManager.GetString("Logsheet_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheet Status.
        /// </summary>
        public static string Logsheet_Status {
            get {
                return ResourceManager.GetString("Logsheet_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheet Summary Report.
        /// </summary>
        public static string LogsheetSummaryReport {
            get {
                return ResourceManager.GetString("LogsheetSummaryReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot History Report.
        /// </summary>
        public static string Lot_History_Report {
            get {
                return ResourceManager.GetString("Lot_History_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot No..
        /// </summary>
        public static string Lot_No {
            get {
                return ResourceManager.GetString("Lot_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot No. Length.
        /// </summary>
        public static string Lot_No_Length {
            get {
                return ResourceManager.GetString("Lot_No_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lot Number Generation.
        /// </summary>
        public static string Lot_Number_Generation {
            get {
                return ResourceManager.GetString("Lot_Number_Generation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual Scan.
        /// </summary>
        public static string Manual_Scan {
            get {
                return ResourceManager.GetString("Manual_Scan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Raw Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incoming Raw Material.
        /// </summary>
        public static string Material_Info {
            get {
                return ResourceManager.GetString("Material_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Material.
        /// </summary>
        public static string Material_Reject {
            get {
                return ResourceManager.GetString("Material_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Raw Material.
        /// </summary>
        public static string Material_Withdraw {
            get {
                return ResourceManager.GetString("Material_Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Charging.
        /// </summary>
        public static string Max_Charging {
            get {
                return ResourceManager.GetString("Max_Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. No. Of Charging.
        /// </summary>
        public static string Max_No_Of_Charging {
            get {
                return ResourceManager.GetString("Max_No_Of_Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. of Changes.
        /// </summary>
        public static string Max_Of_Changes {
            get {
                return ResourceManager.GetString("Max_Of_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Charges.
        /// </summary>
        public static string Max_Of_Charges {
            get {
                return ResourceManager.GetString("Max_Of_Charges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access is denied. User is unauthorized.
        /// </summary>
        public static string Message_Access_Denied {
            get {
                return ResourceManager.GetString("Message_Access_Denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to clone this Logsheet Template?.
        /// </summary>
        public static string Message_Clone_Msg {
            get {
                return ResourceManager.GetString("Message_Clone_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete?.
        /// </summary>
        public static string Message_Delete_Msg {
            get {
                return ResourceManager.GetString("Message_Delete_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is duplicated..
        /// </summary>
        public static string Message_Is_Duplicated {
            get {
                return ResourceManager.GetString("Message_Is_Duplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is invalid..
        /// </summary>
        public static string Message_Is_Invalid {
            get {
                return ResourceManager.GetString("Message_Is_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field is required..
        /// </summary>
        public static string Message_Is_Required {
            get {
                return ResourceManager.GetString("Message_Is_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items duplicate. Please add  items!.
        /// </summary>
        public static string Msg_Items_Duplicate {
            get {
                return ResourceManager.GetString("Msg_Items_Duplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to choose the product?.
        /// </summary>
        public static string Msg_Select_Product {
            get {
                return ResourceManager.GetString("Msg_Select_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to choose the product transaction?.
        /// </summary>
        public static string Msg_Select_Product_Transaction {
            get {
                return ResourceManager.GetString("Msg_Select_Product_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to N/A.
        /// </summary>
        public static string NA {
            get {
                return ResourceManager.GetString("NA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NG.
        /// </summary>
        public static string NG {
            get {
                return ResourceManager.GetString("NG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Charged.
        /// </summary>
        public static string No_Charged {
            get {
                return ResourceManager.GetString("No_Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No. Of Charging.
        /// </summary>
        public static string No_Of_Charging {
            get {
                return ResourceManager.GetString("No_Of_Charging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Containers.
        /// </summary>
        public static string No_Of_Containers {
            get {
                return ResourceManager.GetString("No_Of_Containers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to operation.
        /// </summary>
        public static string Operation {
            get {
                return ResourceManager.GetString("Operation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range From.
        /// </summary>
        public static string Option_Range_From {
            get {
                return ResourceManager.GetString("Option_Range_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range To.
        /// </summary>
        public static string Option_Range_To {
            get {
                return ResourceManager.GetString("Option_Range_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Others.
        /// </summary>
        public static string Others {
            get {
                return ResourceManager.GetString("Others", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package Type.
        /// </summary>
        public static string Package_Type {
            get {
                return ResourceManager.GetString("Package_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        public static string Packaging {
            get {
                return ResourceManager.GetString("Packaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging List.
        /// </summary>
        public static string Packaging_Type {
            get {
                return ResourceManager.GetString("Packaging_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packing.
        /// </summary>
        public static string Packing {
            get {
                return ResourceManager.GetString("Packing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Name.
        /// </summary>
        public static string Page_Name {
            get {
                return ResourceManager.GetString("Page_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Role.
        /// </summary>
        public static string Page_Role {
            get {
                return ResourceManager.GetString("Page_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passed.
        /// </summary>
        public static string Passed {
            get {
                return ResourceManager.GetString("Passed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD.
        /// </summary>
        public static string PD {
            get {
                return ResourceManager.GetString("PD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD Approval.
        /// </summary>
        public static string PD_Approval {
            get {
                return ResourceManager.GetString("PD_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD Date.
        /// </summary>
        public static string PD_Date {
            get {
                return ResourceManager.GetString("PD_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PD Issue.
        /// </summary>
        public static string PD_Issue {
            get {
                return ResourceManager.GetString("PD_Issue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to P.L.C..
        /// </summary>
        public static string PLC {
            get {
                return ResourceManager.GetString("PLC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please circle as appropriate.
        /// </summary>
        public static string Please_Circle_As_Appropriate {
            get {
                return ResourceManager.GetString("Please_Circle_As_Appropriate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pls Tick.
        /// </summary>
        public static string Pls_Tick {
            get {
                return ResourceManager.GetString("Pls_Tick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Form.
        /// </summary>
        public static string Print_Form {
            get {
                return ResourceManager.GetString("Print_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pass.
        /// </summary>
        public static string Print_Pass {
            get {
                return ResourceManager.GetString("Print_Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Pending.
        /// </summary>
        public static string Print_Pending {
            get {
                return ResourceManager.GetString("Print_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Reject.
        /// </summary>
        public static string Print_Reject {
            get {
                return ResourceManager.GetString("Print_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Report.
        /// </summary>
        public static string Print_Report {
            get {
                return ResourceManager.GetString("Print_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code.
        /// </summary>
        public static string Product_Code {
            get {
                return ResourceManager.GetString("Product_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Code Length.
        /// </summary>
        public static string Product_Code_Length {
            get {
                return ResourceManager.GetString("Product_Code_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product List.
        /// </summary>
        public static string Product_List {
            get {
                return ResourceManager.GetString("Product_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        public static string Product_Name {
            get {
                return ResourceManager.GetString("Product_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product No..
        /// </summary>
        public static string Product_No {
            get {
                return ResourceManager.GetString("Product_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Status Form.
        /// </summary>
        public static string Product_Status_Form {
            get {
                return ResourceManager.GetString("Product_Status_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string Project_Name {
            get {
                return ResourceManager.GetString("Project_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prum Code.
        /// </summary>
        public static string Prum_Code {
            get {
                return ResourceManager.GetString("Prum_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge Drum.
        /// </summary>
        public static string Purge_Drum {
            get {
                return ResourceManager.GetString("Purge_Drum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purge History Report.
        /// </summary>
        public static string Purge_History_Report {
            get {
                return ResourceManager.GetString("Purge_History_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purging Process.
        /// </summary>
        public static string Purging_Process {
            get {
                return ResourceManager.GetString("Purging_Process", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA.
        /// </summary>
        public static string QA {
            get {
                return ResourceManager.GetString("QA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Approval.
        /// </summary>
        public static string QA_Approval {
            get {
                return ResourceManager.GetString("QA_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QA Date.
        /// </summary>
        public static string QA_Date {
            get {
                return ResourceManager.GetString("QA_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised by QA Staff.
        /// </summary>
        public static string QA_Staff {
            get {
                return ResourceManager.GetString("QA_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qty.
        /// </summary>
        public static string Qty_Withdraw {
            get {
                return ResourceManager.GetString("Qty_Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Scanned.
        /// </summary>
        public static string Quantity_Scanned {
            get {
                return ResourceManager.GetString("Quantity_Scanned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raised by QA staff.
        /// </summary>
        public static string Raised_By_QA_Staff {
            get {
                return ResourceManager.GetString("Raised_By_QA_Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range from.
        /// </summary>
        public static string Range_From {
            get {
                return ResourceManager.GetString("Range_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raw Material Inventory Record.
        /// </summary>
        public static string Raw_Material_Inventory_Record {
            get {
                return ResourceManager.GetString("Raw_Material_Inventory_Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-inspection on rework.
        /// </summary>
        public static string Re_Inspection_On_Rework {
            get {
                return ResourceManager.GetString("Re_Inspection_On_Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason If Reject.
        /// </summary>
        public static string Reason_If_Reject {
            get {
                return ResourceManager.GetString("Reason_If_Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason If Pending/Reject.
        /// </summary>
        public static string Reason_If_Reject_Product_Form {
            get {
                return ResourceManager.GetString("Reason_If_Reject_Product_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Date.
        /// </summary>
        public static string Received_Date {
            get {
                return ResourceManager.GetString("Received_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Quantity.
        /// </summary>
        public static string Received_Qty {
            get {
                return ResourceManager.GetString("Received_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Receiving Date.
        /// </summary>
        public static string Receiving_Date {
            get {
                return ResourceManager.GetString("Receiving_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record By.
        /// </summary>
        public static string Record_By {
            get {
                return ResourceManager.GetString("Record_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        public static string Reject_Customer_Name {
            get {
                return ResourceManager.GetString("Reject_Customer_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject from.
        /// </summary>
        public static string Reject_From {
            get {
                return ResourceManager.GetString("Reject_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inhouse Location.
        /// </summary>
        public static string Reject_Inhouse_Location {
            get {
                return ResourceManager.GetString("Reject_Inhouse_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Matrials.
        /// </summary>
        public static string Reject_Matrials {
            get {
                return ResourceManager.GetString("Reject_Matrials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Materials Report.
        /// </summary>
        public static string Reject_Matrials_Report {
            get {
                return ResourceManager.GetString("Reject_Matrials_Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason if Reject.
        /// </summary>
        public static string Reject_Reason {
            get {
                return ResourceManager.GetString("Reject_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass/Fail.
        /// </summary>
        public static string Reject_Status {
            get {
                return ResourceManager.GetString("Reject_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier Name.
        /// </summary>
        public static string Reject_Supplier_Name {
            get {
                return ResourceManager.GetString("Reject_Supplier_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remarks.
        /// </summary>
        public static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Date.
        /// </summary>
        public static string Report_Date {
            get {
                return ResourceManager.GetString("Report_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        public static string Reports {
            get {
                return ResourceManager.GetString("Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Reset_Password {
            get {
                return ResourceManager.GetString("Reset_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password Complete.
        /// </summary>
        public static string Reset_Password_Complete {
            get {
                return ResourceManager.GetString("Reset_Password_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve.
        /// </summary>
        public static string Retrieve {
            get {
                return ResourceManager.GetString("Retrieve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to External Provider.
        /// </summary>
        public static string Return_To_External_Provider {
            get {
                return ResourceManager.GetString("Return_To_External_Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return to Supplier.
        /// </summary>
        public static string Return_To_Supplier {
            get {
                return ResourceManager.GetString("Return_To_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review within 6 months, email to notify.
        /// </summary>
        public static string Review_6_Month_Notify {
            get {
                return ResourceManager.GetString("Review_6_Month_Notify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Date.
        /// </summary>
        public static string Review_Date {
            get {
                return ResourceManager.GetString("Review_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reviewed Date.
        /// </summary>
        public static string Reviewed_Date {
            get {
                return ResourceManager.GetString("Reviewed_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision.
        /// </summary>
        public static string Revision {
            get {
                return ResourceManager.GetString("Revision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revision No..
        /// </summary>
        public static string Revision_No {
            get {
                return ResourceManager.GetString("Revision_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rework.
        /// </summary>
        public static string Rework {
            get {
                return ResourceManager.GetString("Rework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RMR No..
        /// </summary>
        public static string RMR_No {
            get {
                return ResourceManager.GetString("RMR_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string Role_Name {
            get {
                return ResourceManager.GetString("Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Setup.
        /// </summary>
        public static string Role_Setup {
            get {
                return ResourceManager.GetString("Role_Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTE.
        /// </summary>
        public static string RTE {
            get {
                return ResourceManager.GetString("RTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RTS.
        /// </summary>
        public static string RTS {
            get {
                return ResourceManager.GetString("RTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running Number.
        /// </summary>
        public static string Running_Number {
            get {
                return ResourceManager.GetString("Running_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales.
        /// </summary>
        public static string Sales {
            get {
                return ResourceManager.GetString("Sales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sales Date.
        /// </summary>
        public static string Sales_Date {
            get {
                return ResourceManager.GetString("Sales_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Close.
        /// </summary>
        public static string Save_And_Close {
            get {
                return ResourceManager.GetString("Save_And_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; New.
        /// </summary>
        public static string Save_And_New {
            get {
                return ResourceManager.GetString("Save_And_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; View Detail.
        /// </summary>
        public static string Save_And_View_Detail {
            get {
                return ResourceManager.GetString("Save_And_View_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string Save_Changes {
            get {
                return ResourceManager.GetString("Save_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Print.
        /// </summary>
        public static string Save_Print {
            get {
                return ResourceManager.GetString("Save_Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Print Form.
        /// </summary>
        public static string Save_Print_Form {
            get {
                return ResourceManager.GetString("Save_Print_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Print Product Form.
        /// </summary>
        public static string Save_Print_Product_Form {
            get {
                return ResourceManager.GetString("Save_Print_Product_Form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scrap.
        /// </summary>
        public static string Scrap {
            get {
                return ResourceManager.GetString("Scrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial No..
        /// </summary>
        public static string Serial_No {
            get {
                return ResourceManager.GetString("Serial_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string Signature {
            get {
                return ResourceManager.GetString("Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signed by MRT.
        /// </summary>
        public static string Signed_By_MRT {
            get {
                return ResourceManager.GetString("Signed_By_MRT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip Purging.
        /// </summary>
        public static string Skip_Purging {
            get {
                return ResourceManager.GetString("Skip_Purging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By.
        /// </summary>
        public static string Sort_By {
            get {
                return ResourceManager.GetString("Sort_By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station.
        /// </summary>
        public static string Station {
            get {
                return ResourceManager.GetString("Station", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Station Code.
        /// </summary>
        public static string Station_Code {
            get {
                return ResourceManager.GetString("Station_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Transaction.
        /// </summary>
        public static string Successful_Transaction {
            get {
                return ResourceManager.GetString("Successful_Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier.
        /// </summary>
        public static string Supplier {
            get {
                return ResourceManager.GetString("Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank No..
        /// </summary>
        public static string Tank_No {
            get {
                return ResourceManager.GetString("Tank_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Code.
        /// </summary>
        public static string Template_Code {
            get {
                return ResourceManager.GetString("Template_Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Components.
        /// </summary>
        public static string Template_Components {
            get {
                return ResourceManager.GetString("Template_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheet Template.
        /// </summary>
        public static string Template_ID {
            get {
                return ResourceManager.GetString("Template_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logsheet Template.
        /// </summary>
        public static string Template_Logsheet {
            get {
                return ResourceManager.GetString("Template_Logsheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template Name.
        /// </summary>
        public static string Template_Name {
            get {
                return ResourceManager.GetString("Template_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template to Product.
        /// </summary>
        public static string Template_To_Product {
            get {
                return ResourceManager.GetString("Template_To_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The.
        /// </summary>
        public static string The {
            get {
                return ResourceManager.GetString("The", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Time.
        /// </summary>
        public static string To_Time {
            get {
                return ResourceManager.GetString("To_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Quantity on Hand.
        /// </summary>
        public static string Total_Quatity_On_Hand {
            get {
                return ResourceManager.GetString("Total_Quatity_On_Hand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Receiving.
        /// </summary>
        public static string Total_Receiving {
            get {
                return ResourceManager.GetString("Total_Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction Date.
        /// </summary>
        public static string Transaction_Date {
            get {
                return ResourceManager.GetString("Transaction_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfered Date.
        /// </summary>
        public static string Transferring_Date {
            get {
                return ResourceManager.GetString("Transferring_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UAI.
        /// </summary>
        public static string UAI {
            get {
                return ResourceManager.GetString("UAI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UOM.
        /// </summary>
        public static string Unit_of_Measure {
            get {
                return ResourceManager.GetString("Unit_of_Measure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string User_Information {
            get {
                return ResourceManager.GetString("User_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person in charge.
        /// </summary>
        public static string User_Who_Charged {
            get {
                return ResourceManager.GetString("User_Who_Charged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        public static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Date.
        /// </summary>
        public static string Withdraw_Date {
            get {
                return ResourceManager.GetString("Withdraw_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Tank.
        /// </summary>
        public static string Withdraw_From {
            get {
                return ResourceManager.GetString("Withdraw_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Tank.
        /// </summary>
        public static string Withdraw_To {
            get {
                return ResourceManager.GetString("Withdraw_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order No..
        /// </summary>
        public static string Work_Order_No {
            get {
                return ResourceManager.GetString("Work_Order_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
